/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package bhaskar.looser.FAH.ui;

import java.awt.Image;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 * @author 360758
 */
public class masterFrame extends javax.swing.JFrame {

    
    /**
     * Creates new form masterFrame
     */
    public masterFrame() {
        initComponents();
        try
    {
    Image thoughtIcon = ImageIO.read(getClass().getResource("../res/thoughtIcon.png"));
    Image ideaIcon = ImageIO.read(getClass().getResource("../res/ideaIcon.png"));
    Image workIcon = ImageIO.read(getClass().getResource("../res/workIcon.jpg"));
    thoughtButton.setIcon(new ImageIcon(thoughtIcon));
    ideaButton.setIcon(new ImageIcon(ideaIcon));
    workButton.setIcon(new ImageIcon(workIcon));
    }catch(IOException e){}
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        thoughtButton = new javax.swing.JButton();
        ideaButton = new javax.swing.JButton();
        workButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 300));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Hi there! how are you doing??");

        thoughtButton.setBackground(new java.awt.Color(255, 255, 255));
        thoughtButton.setText("Thought");
        thoughtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                thoughtButtonActionPerformed(evt);
            }
        });

        ideaButton.setBackground(new java.awt.Color(255, 255, 255));
        ideaButton.setText("Idea");

        workButton.setBackground(new java.awt.Color(255, 255, 255));
        workButton.setText("Work");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(thoughtButton)
                        .addGap(18, 18, 18)
                        .addComponent(ideaButton)
                        .addGap(18, 18, 18)
                        .addComponent(workButton)))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(thoughtButton)
                    .addComponent(ideaButton)
                    .addComponent(workButton))
                .addContainerGap(226, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void thoughtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_thoughtButtonActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_thoughtButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(masterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(masterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(masterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(masterFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new masterFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ideaButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton thoughtButton;
    private javax.swing.JButton workButton;
    // End of variables declaration//GEN-END:variables
}
